### ISSUE TITLE
Exception when distributed tracing is enabled and using ASP.NET Core RequestLocalization middleware

### ISSUE THREAD

**Issue by alanwest** [newrelic/newrelic-dotnet-agent#22]
## Description

Agent causes exception when distributed tracing is enabled and ASP.NET Core application uses the `RequestLocalization` middleware. Appears to affect ASP.NET Core apps running on Linux in a docker container.

## Steps to Reproduce

Create new Web API
```
mkdir locale
cd locale
dotnet new webapi
```

Add the RequestLocalization middleware in `Startup.cs`
```csharp
var supportedCultures = new[]
{
    new CultureInfo("en-US"),
    new CultureInfo("ar"),
};

app.UseRequestLocalization(new RequestLocalizationOptions
{
    DefaultRequestCulture = new RequestCulture("en-US"),
    SupportedCultures = supportedCultures
});
```

Add the following controller
```csharp
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RequestLocalization.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class TestController : ControllerBase
    {
        [HttpGet]
        public async Task<string> Get()
        {
            using (var client = new System.Net.Http.HttpClient())
            {
                return await client.GetStringAsync("https://newrelic.com");
            }
        }
    }
}
```

Create a `Dockerfile` and replace `put_license_key_here`
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.0

RUN curl -O https://download.newrelic.com/dot_net_agent/latest_release/newrelic-netcore20-agent_8.29.0.0_amd64.deb
RUN dpkg -i ./newrelic-netcore20-agent*.deb

ENV CORECLR_NEWRELIC_HOME /usr/local/newrelic-netcore20-agent
ENV NEW_RELIC_LICENSE_KEY put_license_key_here

WORKDIR /app
COPY ./bin/Debug/netcoreapp3.1/publish .

EXPOSE 5000

ENTRYPOINT ["/bin/bash", "-c", "dotnet locale.dll"]
```

Create a `docker-compose.yml` file
```
version: "3"

services:
  locale:
    image: locale:latest
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_URLS: http://*:5000
      ASPNETCORE_ENVIRONMENT: Development
      CORECLR_ENABLE_PROFILING: 1
      CORECLR_PROFILER: "{36032161-FFC0-4B61-B559-F6C5D41BAE5A}"
      CORECLR_PROFILER_PATH: /usr/local/newrelic-netcore20-agent/libNewRelicProfiler.so
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
``` 

Publish and run the application
```
dotnet publish
docker build -t locale .
docker-compose up
```

Hit the endpoint
```
curl -s -H 'Accept-Language: ar' -XGET http://localhost:5000/Test
```

You will get the following exception:
```
System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters.
```
