### ISSUE TITLE
Syntax error in /build/Linux/build/common/setenv.sh

### ISSUE THREAD

**Issue by Lilstritz** [newrelic/newrelic-dotnet-agent#2863]
There's a syntax error in the file /build/Linux/build/common/setenv.sh

![Screenshot 2024-10-31 at 1 53 04 PM](https://github.com/user-attachments/assets/d499c173-9219-42d8-ba29-7d82c06d7f19)

**Description**
A recent build in my team's CI pipeline failed with the error `/usr/local/newrelic-dotnet-agent/setenv.sh: line 3: syntax error near unexpected token '&&'`

**Expected Behavior**
Build doesn't fail. Syntax is correct.

**The problem**:
(I believe?) The first semicolon should be removed: https://github.com/newrelic/newrelic-dotnet-agent/blob/main/build/Linux/build/common/setenv.sh#L3

Introduced in https://github.com/newrelic/newrelic-dotnet-agent/pull/2852

Apologies if I'm missing anything.

**Comment by Lilstritz** [comment]
I tried to push a branch with the fix but I got a 403. I've never attempted to contribute to a public repo before so I don't know the rules. In any case, I _think_ / hope this is straightforward enough.

**Comment by tippmar-nr** [comment]
@Lilstritz Thanks for your report - the fix was easy enough. Next time, you can fork our repo, make a change in a branch on your fork and then open a PR to our repo with the change.

**Comment by Lilstritz** [comment]
Thanks for the quick turnaround and thanks for the information.

**Comment by Lilstritz** [comment]
This issue inspired me to add `shellcheck` to my team's codebase's CI pipelines. I attempted to apply the same change in this codebase, but I ran into some nontrivial shell errors that I have no business meddling with in this codebase.

But in case it interests anybody, applying the check for me was fairly straightforward, and I'll leave the github workflow instructions here in case anybody wants to take a shot at cleaning up the shell errors and integrating a shell linter into the CI pipeline.

```yml
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          find ${{ github.workspace }} -name "*.sh" -exec shellcheck --severity=error {} +
```
